const cores = [
  "AliceBlue",
  "AntiqueWhite",
  "Aqua",
  "Aquamarine",
  "Azure",
  "Beige",
  "Bisque",
  "Black",
  "BlanchedAlmond",
  "Blue",
  "BlueViolet",
  "Brown",
  "BurlyWood",
  "CadetBlue",
  "Chartreuse",
  "Chocolate",
  "Coral",
  "CornflowerBlue",
  "Cornsilk",
  "Crimson",
  "Cyan",
  "DarkBlue",
  "DarkCyan",
  "DarkGoldenRod",
  "DarkGray",
  "DarkGreen",
  "DarkKhaki",
  "DarkMagenta",
  "DarkOliveGreen",
  "DarkOrange",
  "DarkOrchid",
  "DarkRed",
  "DarkSalmon",
  "DarkSeaGreen",
  "DarkSlateBlue",
  "DarkSlateGray",
  "DarkTurquoise",
  "DarkViolet",
  "DeepPink",
  "DeepSkyBlue",
  "DimGray",
  "DodgerBlue",
  "FireBrick",
  "FloralWhite",
  "ForestGreen",
  "Fuchsia",
  "Gainsboro",
  "GhostWhite",
  "Gold",
  "GoldenRod",
  "Gray",
  "Green",
  "GreenYellow",
  "HoneyDew",
  "HotPink",
  "IndianRed",
  "Indigo",
  "Ivory",
  "Khaki",
  "Lavender",
  "LavenderBlush",
  "LawnGreen",
  "LemonChiffon",
  "LightBlue",
  "LightCoral",
  "LightCyan",
  "LightGoldenRodYellow",
  "LightGray",
  "LightGreen",
  "LightPink",
  "LightSalmon",
  "LightSeaGreen",
  "LightSkyBlue",
  "LightSlateGray",
  "LightSteelBlue",
  "LightYellow",
  "Lime",
  "LimeGreen",
  "Linen",
  "Magenta",
  "Maroon",
  "MediumAquaMarine",
  "MediumBlue",
  "MediumOrchid",
  "MediumPurple",
  "MediumSeaGreen",
  "MediumSlateBlue",
  "MediumSpringGreen",
  "MediumTurquoise",
  "MediumVioletRed",
  "MidnightBlue",
  "MintCream",
  "MistyRose",
  "Moccasin",
  "NavajoWhite",
  "Navy",
  "OldLace",
  "Olive",
  "OliveDrab",
  "Orange",
  "OrangeRed",
  "Orchid",
  "PaleGoldenRod",
  "PaleGreen",
  "PaleTurquoise",
  "PaleVioletRed",
  "PapayaWhip",
  "PeachPuff",
  "Peru",
  "Pink",
  "Plum",
  "PowderBlue",
  "Purple",
  "RebeccaPurple",
  "Red",
  "RosyBrown",
  "RoyalBlue",
  "SaddleBrown",
  "Salmon",
  "SandyBrown",
  "SeaGreen",
  "SeaShell",
  "Sienna",
  "Silver",
  "SkyBlue",
  "SlateBlue",
  "SlateGray",
  "Snow",
  "SpringGreen",
  "SteelBlue",
  "Tan",
  "Teal",
  "Thistle",
  "Tomato",
  "Turquoise",
  "Violet",
  "Wheat",
  "White",
  "WhiteSmoke",
  "Yellow",
  "YellowGreen",
];

const coresEmPortugues = [
  "Branco Alabastro",
  "Branco Antigo",
  "Água",
  "Água Mariana",
  "Azul Celeste",
  "Bege",
  "Bisque",
  "Preto",
  "Amêndoa Clareada",
  "Azul",
  "Azul Violeta",
  "Marrom",
  "Madeira Queimada",
  "Azul Cadete",
  "Amarelo Verde",
  "Chocolate",
  "Coral",
  "Azul Flor de Milho",
  "Seda do Milho",
  "Carmin",
  "Ciano",
  "Azul Escuro",
  "Ciano Escuro",
  "Ouro Velho",
  "Cinza Escuro",
  "Verde Escuro",
  "Cáqui Escuro",
  "Magenta Escuro",
  "Verde Oliva Escuro",
  "Laranja Escuro",
  "Orquídea Escura",
  "Vermelho Escuro",
  "Salmão Escuro",
  "Verde Mar Escuro",
  "Azul Ardósia Escuro",
  "Cinza Ardósia Escuro",
  "Turquesa Escuro",
  "Violeta Escuro",
  "Rosa Profundo",
  "Azul Profundo",
  "Cinza Escuro",
  "Azul Dodger",
  "Tijolo Vermelho",
  "Branco Floral",
  "Verde Floresta",
  "Fúcsia",
  "Gainsboro",
  "Branco Fantasma",
  "Ouro",
  "Vara Dourada",
  "Cinza",
  "Verde",
  "Amarelo Verde",
  "Orvalho do Mel",
  "Rosa Quente",
  "Vermelho Índio",
  "Anil",
  "Marfim",
  "Cáqui",
  "Lavanda",
  "Rubor de Lavanda",
  "Verde Gramado",
  "Chiffon de Limão",
  "Azul Claro",
  "Coral Claro",
  "Ciano Claro",
  "Amarelo Ouro Claro",
  "Cinza Claro",
  "Verde Claro",
  "Rosa Claro",
  "Salmão Claro",
  "Verde Mar Claro",
  "Azul Céu Claro",
  "Ardósia Cinza Claro",
  "Azul Aço Claro",
  "Amarelo Claro",
  "Lima",
  "Verde Lima",
  "Linho",
  "Magenta",
  "Marrom",
  "Verde Militar",
  "Azul Navy",
  "Renda Antiga",
  "Oliva",
  "Oliva Drab",
  "Laranja",
  "Vermelho Laranja",
  "Orquídea",
  "Palha Ouro Pálido",
  "Verde Pálido",
  "Turquesa Pálido",
  "Vermelho Violeta Pálido",
  "Creme de Papaya",
  "Pêssego",
  "Peru",
  "Rosa",
  "Ameixa",
  "Azul Pó",
  "Púrpura",
  "Roxo Rebecca",
  "Vermelho",
  "Marrom Rosa",
  "Azul Royal",
  "Saddle Brown",
  "Salmão",
  "Bege Avermelhado",
  "Marinha",
  "Açúcar Mascavo",
  "Verde Mar",
  "Marfim",
  "Aqua Primavera",
  "Aço Azul",
  "Canela",
  "Azul Petróleo",
  "Uva",
  "Tomate",
  "Turquesa",
  "Violeta",
  "Trigo",
  "Branco Puro",
  "Fumaça Branca",
  "Amarelo",
  "Verde Amarelo",
];

const btn = document.getElementById("btn");
const cor = document.querySelector(".cor");

btn.addEventListener("click", function () {
  const corAleatoria = gerarCorAleatoria();
  document.body.style.background = cores[corAleatoria];
  console.log(corAleatoria);
  cor.textContent = cores[corAleatoria];
  //cor.textContent = coresEmPortugues[corAleatoria];
});

function gerarCorAleatoria() {
  return Math.floor(Math.random() * cores.length);
}
